### ISSUE TITLE
DB2 or IMS Scheduling and Batch Link Queue for CA InterTest Batch

### ISSUE THREAD

**Issue by dpyoho** [BroadcomMFD/debugger-for-mainframe#7]
Hello,

Does this plugin support editing/viewing the DB2/IMS Scheduling table and/or attaching and starting a debug session from the Batch Link Queue for CA InterTest Batch? Like the Eclipse plugin does.

**CA InterTest**: Batch Link Facility
https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-intertest-and-ca-symdump/11-0/using-batch-tools/batch-debugging/batch-link-facility.html

**CA InterTest Eclipse**: Use Schedule to Improve DB2 or IMS/DC Debugging
https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-intertest-eclipse-help/11-0/ca-intertest-help/scheduling-for-db2-sp-and-ims-dc-debugging/use-schedule-to-improve-db2-or-ims-dc-debugging.html

**Comment by zimlu02** [comment]
Released in [1.8.0 ](https://github.com/BroadcomMFD/debugger-for-mainframe/releases/tag/v1.8.0)
